### ISSUE TITLE
Suggesting a feature for Deadname remover.

### ISSUE THREAD

**Issue by alice-tastic** [WillHayCode/Deadname-Remover#127]
I use the deadname remover, but I think it is lacking versatility. My deadname shows up with my full deadname, and my dead nickname, and want to be able to remove both versions.

**Comment by Ellii13** [comment]
Can u maybe write it so that it's a plugin not just for the browser but for the whole phone/pc?

**Comment by RetroAsgardian** [comment]
@Ellii13 Unfortunately, it's not that simple. A WebExtension is completely unable to interact with anything outside the Chrome/Firefox/etc. window. It would require a full rewrite as a standalone application in order to access system APIs.

There *might* potentially be a low-level Windows API to hijack text rendering; however, that functionality is almost definitely not exposed on Mac OS, Linux, Android, or iOS.

One bodge I can think of would be to edit a font and add a ligature for your deadname that displays it as a censor bar or something else. Then, if you set that as your system font, it should block out all instances of your deadname across the UI.

**Comment by Gusted** [comment]
#132
