### ISSUE TITLE
[Bug?] Extension maxes out CPU thread when enabled (Firefox 75, Ubuntu 20.04)

### ISSUE THREAD

**Issue by aksipwn** [WillHayCode/Deadname-Remover#7]
basically what it says on the tin: whenever the extension is enabled, one of my cpu cores is constantly maxed out. [evidence](https://i.imgur.com/mwN0U9h.mp4)

**Comment by evelynhathaway** [comment]
I can reproduce this by just idling on one tab with the injected content script. Here are the issues I detected and the best ways to fix them.

| Issue                                                                              | Cause                                                                                                                                                                                              | Recommendation                                                                                                                                                                                |
| ---------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Timer repeats at the loading interval (default `50ms`)                             | `loadingInterval` isn't cleared because the [`readyState` check](https://github.com/WillHayCode/Deadname-Remover/blob/c1928e3526ad59fbfe89931aa21e90aa023c0124/src/inject.ts#L15) only occurs once | Check the `readyState` whenever firing the `loadingInterval` callback                                                                                                                         |
| Script checks every node even if nothing has changed                               | Timers have no way of detecting changes                                                                                                                                                            | Use [`MutationObserver`s](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and mutate the changed or added nodes as they are sent                                           |
| Deadnames aren't replaced quickly on page load, even with a short loading interval | Content script is injected when idle                                                                                                                                                               | Investigate which [content script runtime](https://developer.chrome.com/extensions/content_scripts#run_time) best balances performance speed (this may be influenced by timers vs. observers) |

**Comment by WillHayCode** [comment]
I was looking into possible solutions, and those recommendations are excellent @evelynhathaway ! Thank you so much. Not in the next update, but the following update these will be top priority.
